// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ethereum/go-ethereum/ethclient"
)

// Injectors from wire.go:

func WireApp(configPath string) (*App, error) {
	config, err := LoadConfig(configPath)
	if err != nil {
		return nil, err
	}
	mainTokensDB := NewTokensDB()
	accounts := NewAccounts(config)
	mainTelegram := NewTelegram(config)
	client, err := newEthClient(config)
	if err != nil {
		return nil, err
	}
	mainTokensManager := NewTokensManager(client, mainTokensDB)
	app := NewApp(config, mainTokensDB, accounts, mainTelegram, client, mainTokensManager)
	return app, nil
}

// wire.go:

func newEthClient(config *Config) (*ethclient.Client, error) {
	return ethclient.Dial(config.EthUrl)
}
